name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v1  
      with:
        registry: edaascontainerregistry.azurecr.cn
        username: edaascontainerregistry
        password: f7O8rZTJ/pSE2R0GhYnVkS8MM2mFh11t
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        
    
